// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ilseman.phonebook.domain;

import com.ilseman.phonebook.domain.ListingDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ListingDataOnDemand_Roo_Configurable {
    
    declare @type: ListingDataOnDemand: @Configurable;
    
}
