// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ilseman.phonebook.domain;

import com.ilseman.phonebook.domain.Listing;
import com.ilseman.phonebook.domain.ListingDataOnDemand;
import com.ilseman.phonebook.domain.ListingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ListingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ListingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ListingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ListingIntegrationTest: @Transactional;
    
    @Autowired
    ListingDataOnDemand ListingIntegrationTest.dod;
    
    @Test
    public void ListingIntegrationTest.testCountListings() {
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", dod.getRandomListing());
        long count = Listing.countListings();
        Assert.assertTrue("Counter for 'Listing' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ListingIntegrationTest.testFindListing() {
        Listing obj = dod.getRandomListing();
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Listing' failed to provide an identifier", id);
        obj = Listing.findListing(id);
        Assert.assertNotNull("Find method for 'Listing' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Listing' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ListingIntegrationTest.testFindAllListings() {
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", dod.getRandomListing());
        long count = Listing.countListings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Listing', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Listing> result = Listing.findAllListings();
        Assert.assertNotNull("Find all method for 'Listing' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Listing' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ListingIntegrationTest.testFindListingEntries() {
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", dod.getRandomListing());
        long count = Listing.countListings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Listing> result = Listing.findListingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Listing' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Listing' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ListingIntegrationTest.testFlush() {
        Listing obj = dod.getRandomListing();
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Listing' failed to provide an identifier", id);
        obj = Listing.findListing(id);
        Assert.assertNotNull("Find method for 'Listing' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyListing(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Listing' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ListingIntegrationTest.testMergeUpdate() {
        Listing obj = dod.getRandomListing();
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Listing' failed to provide an identifier", id);
        obj = Listing.findListing(id);
        boolean modified =  dod.modifyListing(obj);
        Integer currentVersion = obj.getVersion();
        Listing merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Listing' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ListingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", dod.getRandomListing());
        Listing obj = dod.getNewTransientListing(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Listing' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Listing' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Listing' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ListingIntegrationTest.testRemove() {
        Listing obj = dod.getRandomListing();
        Assert.assertNotNull("Data on demand for 'Listing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Listing' failed to provide an identifier", id);
        obj = Listing.findListing(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Listing' with identifier '" + id + "'", Listing.findListing(id));
    }
    
}
